### ISSUE TITLE
Deleting a non-existent engine throws exception

### ISSUE THREAD

**Issue by miazamrai** [RelationalAI/rai-sdk-csharp#27]
Deleting a non-existent engine throws the following exception

Unhandled exception: RelationalAI.Errors.NotFoundException: {"status":"Not Found","message":"engine not found"}

   at RelationalAI.Services.Rest.EnsureSuccessResponseAsync(HttpResponseMessage response) in /Users/iazam/dev/rai-sdk-csharp/RelationalAI/Services/Rest.cs:line 285
   at RelationalAI.Services.Rest.RequestHelperAsync(String method, String url, Object data, Dictionary`2 headers, Dictionary`2 parameters) in /Users/iazam/dev/rai-sdk-csharp/RelationalAI/Services/Rest.cs:line 350
   at RelationalAI.Services.Rest.RequestAsync(String method, String url, Object data, Dictionary`2 headers, Dictionary`2 parameters) in /Users/iazam/dev/rai-sdk-csharp/RelationalAI/Services/Rest.cs:line 123
   at RelationalAI.Services.Client.DeleteEngineAsync(String engine) in /Users/iazam/dev/rai-sdk-csharp/RelationalAI/Services/Client.cs:line 190
   at RelationalAI.Examples.DeleteEngine.Run(String engine, String profile) in /Users/iazam/dev/rai-sdk-csharp/RelationalAI.Examples/DeleteEngine.cs:line 35
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by miazamrai** [comment]
Working as desired.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6834](https://relationalai.atlassian.net/browse/RAI-6834).

_This link is only accessible to employees of RelationalAI._
